export const daisyUiThemes = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
] as const

export const profilePhoto = "https://avatars.githubusercontent.com/u/77455764?s=400&u=8c9c3b98363535715dafdaeb3f329df9f3493dc7&v=4"

export const coverLetter = `Three years ago I started coding by myself, learning the basics on Python, to the point of making a character generator for a dungeons and dragons kind game. I remained attached to coding and continued programming whenever I had an idea. Then I entered a Full Stack Developer bootcamp, where I learned JavaScript and TypeScript (today I’m teaching React and NodeJS here). From here I landed a job at a startup, my role being maintaining a PWA app in Vue and NodeJS. I continued learning Go and did a freelance project that manipulates git repos. I have an advanced level on English, reading and communicating. I’m looking for a dynamic environment to test myself. Fintechs, e commerce, backend environment. I am eager to learn new techniques to open new goals.`
